# Generated by Django 4.1.7 on 2023-03-04 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='images/profile/')),
                ('about', models.CharField(max_length=500)),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('education', models.TextField()),
                ('company', models.TextField()),
                ('hobby', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
