# Generated by Django 4.1.7 on 2023-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.TextField(default=None),
        ),
    ]
