# Generated by Django 4.1.7 on 2023-03-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_city_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
