# Generated by Django 4.1.7 on 2023-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_avatar_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/DEFAULT_AVATAR.png', upload_to='images/profile_avatars/'),
        ),
    ]
